site_name: till.io
site_description: till - lightweight ML deployment
site_url: https://till.till-io.com/
theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: deep orange
  icon:
    repo: fontawesome/brands/github-alt
  logo: img/icon-white.svg
  favicon: img/favicon.png
  language: en
repo_name: till-io/till
repo_url: https://github.com/till-io/till.git
edit_uri: ''
plugins:
- search
nav:
- till: index.md
- Python:
  - python-main.md
- R:
  - r-main.md
markdown_extensions:
- toc:
    permalink: true
- markdown.extensions.codehilite:
    guess_lang: true
- markdown_include.include:
    base_path: docs
- admonition
- codehilite
- extra
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_div_format ''
- pymdownx.tabbed
extra:
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/till-io
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/in/lukas-jan-stroemsdoerfer-a0a631160/
extra_css:
- css/termynal.css
- css/custom.css
extra_javascript:
- https://unpkg.com/mermaid@8.4.6/dist/mermaid.min.js
- js/termynal.js
- js/custom.js
